### ISSUE TITLE
SLNIM-3: Null safety support

### ISSUE THREAD

**Issue by jhuckabee** [stelynx/network_image_mock#4]
Are there any plans to update this package to support null safety?

**Comment by j4qfrost** [comment]
https://github.com/stelynx/network_image_mock/pull/5 pretty straightforward.

**Comment by campovski** [comment]
Yes, I had a plan to migrate all our packages but unfortunately did not have time since Flutter 2 release. Expect #5 to be merged in a matter of hours.

**Comment by campovski** [comment]
Resolved with #5
