### ISSUE TITLE
Still getting network image failures

### ISSUE THREAD

**Issue by xapatjb4** [stelynx/network_image_mock#6]
Hello, 

I've been trying to setup a test to use this package for network image but I'm still getting the exception thrown.

```
Widget makeOther() {
  return MaterialApp(
    home: ProfilePage(),
  );
}

testWidgets('Profile Page', (WidgetTester tester) async {
      await mockNetworkImagesFor(
        () async => await tester.pumpWidget(
          makeOther(),
        ),
      );
```

I get the following exception thrown
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 400,
```
Any ideas on what's going wrong?

**Comment by campovski** [comment]
Thanks for filing the issue and sorry for late response. I will try to look into it today.

**Comment by SilkeNL** [comment]
@campovski  Could you give an update to this?

**Comment by campovski** [comment]
I have updated the dependencies and hopefully version `2.0.1` should now work for you all since the tests are passing.

@xapatjb4 In case it still does not work for you, I would need more information about the `ProfilePage()` source in order to be able to assist you further.

**Comment by SilkeNL** [comment]
I still have version ^1.1.0 because of other dependencies, but mine also doesn't work.

**Comment by campovski** [comment]
@SilkeNL On second thought you are right. The old version does not work with Flutter 2 and we do not plan to support it. The 1.1.0 version should only be used with legacy codebases, those using Flutter 1.

**Comment by xapatjb4** [comment]
Gotcha, I have flutter 2 so closing issue since support is not planned

**Comment by fynsta** [comment]
This still does not work for me (Flutter 3.3.10). It works if you run the tests using `flutter test`, but not using `flutter run <test_file>`. Even if you use the minimal example from the project description (which btw throws an error because `async` and `await` are missing there.
